### ISSUE TITLE
acorn出错时的友好提示

### ISSUE THREAD

**Issue by xinglie** [naij/gulp-magix-combine#1]
在应用acorn分析js代码的情况下，如果js代码本身写的有错误，acorn会报错，但这个错误不友好，无法快速定位是哪个js出的问题。

是否对这块的异常做一个友好错误提示
![wangwang20170116162524](https://cloud.githubusercontent.com/assets/1290017/21975588/7570962a-dc08-11e6-8a6f-272155435a91.png)
![wangwang20170116162531](https://cloud.githubusercontent.com/assets/1290017/21975589/7571b94c-dc08-11e6-99dc-d86acfea193e.png)

**Comment by naij** [comment]
加了解析文件时出错的文件路径，对应版本：[1.0.5](https://www.npmjs.com/package/gulp-magix-combine)
